sync_from_github:
  stage: deploy
  only :
    - main
  script:
    - git config --global user.name "GitLab Bot"
    - git config --global user.email "bot@example.com"

    #clone Github repo
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/yanntafou/ChatGPT 
    - git push github main

  #only:
  #- schedules