stages:
  - sync

sync_to_github:
  stage: sync
  image: alpine:latest
  only:
    - main  # Adjust if you want other branches too
  before_script:
    - apk add --no-cache git openssh
  script:
    - git config --global user.name "GitLab Sync Bot"
    - git config --global user.email "ci@gitlab.com"

    # Clone GitLab repo (already done by GitLab CI), add GitHub as remote
    - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/yanntafou/ChatGPT.git
    - git merge github/main || echo "Merge conflict, manual intervention needed"

    # Force-push to GitHub (careful if histories diverge)
    - git push github HEAD:main
