stages:
  - sync

sync_from_github:
  stage: sync
  script:
    - git config --global user.name "GitLab Bot"
    - git config --global user.email "bot@example.com"
    - git clone https://oauth2:${GITLAB_TOKEN}@gitlab.com/yann_tafou/chatgpt.git github-upstream
    - cd github-upstream
    - git remote add github ../github-upstream
    - git pull github main || echo "Conflict detected — manual resolution needed"

  #only:
  #- schedules