stages:
  - sync

sync_to_github:
  
  stage: sync
  
  image: alpine:latest
  
  only:
    - main 
  
  before_script:
    - apk add --no-cache git bash
    - git config --global user.name "GitLab Sync Bot"
    - git config --global user.email "ci@gitlab.com"
  
  script:
    - echo "There is nothing here"
      
    # pushing to github after merge success 
    #- git push github HEAD:main

