sync_from_github:
  stage: deploy
  
  script:
    - git config --global user.name "GitLab Bot"
    - git config --global user.email "bot@example.com"

    #clone Github repo
    - git remote add github https://yanntafou:$GITHUB_TOKEN@github.com/yanntafou/ChatGPT.git
    - git push github main 

  #only:
  #- schedules